### ISSUE TITLE
4-mic array: LEDs don't light

### ISSUE THREAD

**Issue by fighterii** [snipsco/snips-skill-respeaker#13]
Hello,

I have a RPi3 with the 4-mic respeaker array. The https://github.com/respeaker/4mics_hat pixels_demo works well for me, so i guess my hardware setup should be fine.

When i start the action itself i get the following log:

```
pi@raspberrypi:/var/lib/snips/skills/snips-skill-respeaker $ ./action-app_respeaker [Info] Initilisation Done! 
[Info] Client Id ........... 2wi13Q9c3U
[Info] Program ............. ./action-app_respeaker
[Info] LED Number .......... 10
[Info] Brightness .......... 64
[Info] Device .............. rpi_*
[Info] Nightmode ........... Enabled
[Info] MQTT Bus ............ localhost:1883 
[Info] Press CTRL-C to exit.

[Debug] State is changed to 0
[Debug] Previous thread NONE terminated with success
[Thread] ------> on_idle started
```

I assume that i should see "on_idle" animation now, but the leds remain dark.

I tried to change the LED Number from 3 to 10/12 and various other numbers, but according to Issue https://github.com/snipsco/snips-skill-respeaker/issues/2 it isn't necessary anymore to specify the number of leds. I also tried to change the spi_dev option in the config.ini to spi_dev=0:1 , because in the [implementation ](https://github.com/respeaker/4mics_hat/blob/master/apa102.py#L89) by seedstudio the following line is used:

> self.spi.open(bus, device) # Open SPI port 0, slave device (CS) 1 

```
pi@raspberrypi:~ $ arecord -l
**** Liste der Hardware-Geräte (CAPTURE) ****
Karte 1: seeed4micvoicec [seeed-4mic-voicecard], Gerät 0: bcm2835-i2s-ac10x-codec0 ac10x-codec0-0 []
Sub-Geräte: 0/1
Sub-Gerät #0: subdevice #0
pi@raspberrypi:~ $ ls -al /dev/spi*
crw-rw---- 1 root spi 153, 0 Dez 20 17:19 /dev/spidev0.0
crw-rw---- 1 root spi 153, 1 Dez 20 17:19 /dev/spidev0.1
```

Can anyone share a working config.ini for a 4-mics array on RPi3 here?

**Comment by CoorFun** [comment]
Hi @fighterii : 

This action code was not aimed for ReSpeaker 4-Mic hat. (The reason why it doesn't work is that it requires to switch on the LED power, which is controlled by `GPIO5` )

We are now adding support for it. Please wait for the next update.

**Comment by belzedaar** [comment]
I tried the development "improvement/brightness_control" branch and it works great on Respeaker 4 mics, thanks @CoorFun!

**Comment by CoorFun** [comment]
Hello @belzedaar : 

Yeah! You find the right branch! 

This is not the final version, I am thinking that the `hw_config.json` should be more general (Having both official hardware and customised specification from users), so I probably change this file to a folder which contains all the hardware specification. Please keep following the update, when the final version is done, I will merge it into the master branch. 

Also for those who can't wait to try, please feel free to test the work on this [branch](https://github.com/snipsco/snips-skill-respeaker/tree/improvement/brightness_control)

Thanks!

**Comment by MichaelBitard** [comment]
Amazing, it works really well !

**Comment by tlrider99** [comment]
Hi together,
I have the same problem as fighterii. Is there a solution?
Thanks a lot!

**Comment by MichaelBitard** [comment]
Hello, yes, the branch `improvement/brightness_control` works with the 4-mic respeaker array, you can try it

**Comment by tlrider99** [comment]
Hi Michaël,
thanks for your answer.
I tried it yesterday with the same result. Have I something to do after the installation? I installed the branch 0.52 after the original installation with using sam.

Best regards
Dirk
Am 22. Jan. 2019, 09:07 +0100 schrieb Michaël Bitard <notifications@github.com>:

**Comment by tlrider99** [comment]
Hello everybody,

I have now seen that the hw_spec.json is missing so the branch about sam was not swapped. What do I have to do to swap the versions?

**Comment by tlrider99** [comment]
Hi everybody,
I installed it manually today and now it works fine  :-) . 
Thanks a lot for your work!

**Comment by CoorFun** [comment]
Hello everyone:

The latest update has been merged into the master branch. 

You can now formally update your respeaker skill. For the latest feature information, please carefully go through the readme page.

***Note: If you would update it by using `sam`, please make sure that `sam` is on version `0.0.48`***
