### ISSUE TITLE
go_weak: this is perhaps misspelled

### ISSUE THREAD

**Issue by amishv** [snipsco/snips-skill-respeaker#14]
go_weak	The time when it weak up

Does this mean go_wake  "the time when it wakes us"?

**Comment by CoorFun** [comment]
Hello @amishv : 

Sorry for this misspelled and thanks for reporting. Will fix it very soon!

**Comment by CoorFun** [comment]
Hello @amishv : 

This fix has been merged. Thanks again for reporting.
