### ISSUE TITLE
6-mic array: LEDs don't light

### ISSUE THREAD

**Issue by tlrider99** [snipsco/snips-skill-respeaker#16]
Hi all,
is there any way to include the 6-mic array?

best regards

**Comment by CoorFun** [comment]
Hello @tlrider99 ,

The latest release supports 4-mic hat. I just check that the 6-mic array and 4-mic array has the sam LED configuration. So please install the latest skill code, then manually change the `confing.ini` file.

Fine the line with option key `model`, then change it to:

```
model=respeaker_4_mic_hat
```

This should be working. If yes, please confirm. Then I will add a hardware specification copy and auto detection for 6-mic hat. 

Thanks.

**Comment by tlrider99** [comment]
Good morning,

I installed the latest release yesterday and changed the configure.ini to respeaker_4_mic_hat  but it doesn't work. Do you know if there is the same chip apa102 on the 6-mic-array? I could not find anything about it.

Best regards
Dirk
Am 24. Jan. 2019, 22:58 +0100 schrieb Coor :

**Comment by CoorFun** [comment]
Hello @tlrider99 : 

I just tested with 6 mic array. I used `respeaker_4_mic_hat` configuration. It works well. 

Please try: 

1. stop snips skill server
```
sudo systemctl stop snips-skill-server 
```

2. direct to skill folder 
```
cd /var/lib/snips/skills/snips-skill-respeaker
```

3. run manually with `-d` parameter for debug mode
```
./action-led_animation_1.6.1 -d
```

Now you can see if there are errors or strange outputs. Please feel free to report.

**Comment by CoorFun** [comment]
Hello @tlrider99 : 

Just made an update, it has an official 6 mic specification file and able to auto detect 6 mic hat now. Just re-install the skill by using sam, it should work after. No need to manually change anything.

**Comment by tlrider99** [comment]
Hello Coor,
Thank you for your great and fast work.
I've tried it twice now, but without success. In the config.ini I entered "respeaker_6_mic_hat". What else do I have to do?
[secret]
mqtt_host=localhost
mqtt_port=1883
site_id=default

[global]
model=respeaker_6_mic_hat
led_bri=63
on_idle=true
on_listen=true
on_speak=true
to_mute=true
to_unmute=true
idle_colour=green
listen_colour=blue
speak_colour=purple
mute_colour=yellow
unmute_colour=green
nightmode=true
go_sleep=22:15
go_wake=1:35
feedback_sound=true

[static]
config_ver=0.2

**Comment by CoorFun** [comment]
> Hello @tlrider99 :
> 
> I just tested with 6 mic array. I used `respeaker_4_mic_hat` configuration. It works well.
> 
> Please try:
> 
> 1. stop snips skill server
> 
> ```
> sudo systemctl stop snips-skill-server 
> ```
> 1. direct to skill folder
> 
> ```
> cd /var/lib/snips/skills/snips-skill-respeaker
> ```
> 1. run manually with `-d` parameter for debug mode
> 
> ```
> ./action-led_animation_1.6.1 -d
> ```
> Now you can see if there are errors or strange outputs. Please feel free to report.

Please try to do these steps, then we will see what's the problem

**Comment by tlrider99** [comment]
Hi CoorFun,

I tried it, but there is no action-led_animation_1.6.1, see picture below. I do have a second raspi with a respeaker_4_mic_hat and this is working fine, there I miss the "action-led_animation_1.6.1" too.

![grafik](https://user-images.githubusercontent.com/29237172/51788535-409b6600-217f-11e9-8c64-e5cec254ea8a.png)

Thanks a lot for your support!

**Comment by CoorFun** [comment]
> Hi CoorFun,
> 
> I tried it, but there is no action-led_animation_1.6.1, see picture below. I do have a second raspi with a respeaker_4_mic_hat and this is working fine, there I miss the "action-led_animation_1.6.1" too.
> 
> ![grafik](https://user-images.githubusercontent.com/29237172/51788535-409b6600-217f-11e9-8c64-e5cec254ea8a.png)
> 
> Thanks a lot for your support!

If you do a `ls` command you can see what exactly under this folder. The version is bumped to 1.6.2 now. So try to do `./action-led_animation_1.6.2 -d`

**Comment by tlrider99** [comment]
Hello CoorFun,

on this way the LED's works fine now. 
Great work!

Thanks !

**Comment by CoorFun** [comment]
> Hello CoorFun,
> 
> on this way the LED's works fine now.
> Great work!
> 
> Thanks !

This probably means that `snips-skill-server` does not have the correct permission to execute this program. Please make sure that `_snips-skills` is in the groups: `spi`,`gpio` and `audio`. By adding it to these groups: `sudo usermod -a -G spi,gpio,audio _snips-skills`

**Comment by CoorFun** [comment]
Hi @tlrider99 , I suppose that your question is solved, please feel free to reopen this issue if it doesn't.
