### ISSUE TITLE
typo error in snipsfile for 4 mic

### ISSUE THREAD

**Issue by urbatecte** [snipsco/snips-skill-respeaker#2]
Hi,

It seems that there is a typp error in snipsfile for 4 mic.
    params:
      num_led: 12
instead of 
    params:
      - num_led: 12

Without the -   snipsmanager install lead to no rerror but led are still off when hotword detected.
But I don't give up ;o)
Thanks for your skill.

**Comment by bjay-wk** [comment]
Sorry for the late reply, I will update the skill as soon as possible

**Comment by bjay-wk** [comment]
Hi urbatecte,
I have updated the snips skill, you don't need anymore to specify the number of led.
The snips skill will autodetect the ReSpeaker 4Hat or 2 hat, if installed
