### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by dony71** [snipsco/snips-skill-respeaker#22]
install by executing :
sam install skills -g https://github.com/snipsco/snips-skill-respeaker.git

got error :
> Running setup.sh & generating virtual environment for snips-skill-respeaker
✖ Error setting up virtualenv, one or more actions might not be able to run. Reason :
src/mqtt_pal.c: In function ‘mqtt_pal_recvall’:
src/mqtt_pal.c:66:16: warning: duplicate ‘const’ declaration specifier [-Wduplicate-decl-specifier]
     const void const *start = buf;
                ^~~~~

what could be wrong?

**Comment by CoorFun** [comment]
Hello, 

It seems this is warning comes from installation. Everything should be ok. The issue is that `sam` can not distinguish an error or a warning, it will always report as an error.
