### ISSUE TITLE
[cGPIO_direction] Failed to open gpio direction for writing!

### ISSUE THREAD

**Issue by dony71** [snipsco/snips-skill-respeaker#23]
this must be permission issue
i have run :
>usermod -a -G spi,gpio,audio _snips-skills

and change:
>chgrp gpio /sys/class/gpio/export
chown 660 /sys/class/gpio/export
chgrp gpio /sys/class/gpio/unexport
chgrp 600 /sys/class/gpio/unexport

but issue still exist

ls -la /dev/gpio*
> crw-rw---- 1 root gpio 254, 0 Jan 28  2018 /dev/gpiochip0
crw-rw---- 1 root gpio 254, 1 Jan 28  2018 /dev/gpiochip1
crw-rw---- 1 root gpio 254, 2 Jan 28  2018 /dev/gpiochip2
crw-rw---- 1 root gpio 244, 0 Jan 28  2018 /dev/gpiomem

ls -la /dev/spidev*
> crw-rw---- 1 root spi 153, 0 Jan 28  2018 /dev/spidev0.0
crw-rw---- 1 root spi 153, 1 Jan 28  2018 /dev/spidev0.1

anybody can tell me which i'm missing?

**Comment by dony71** [comment]
nobody knows?
well, worst case then i will run service with user root :(

**Comment by CoorFun** [comment]
Hello,

Normally we shouldn't have any permission issue.
Is this on a Raspberry Pi3? And have you installed the skill by using `sam`?
