### ISSUE TITLE
action respeaker-makerskit failed 3 times in the last 10 seconds, disabling it

### ISSUE THREAD

**Issue by jandru** [snipsco/snips-skill-respeaker#5]
Hello,
Trying to get the AP102 led's to work with snips, the action script is failing:

Jun  7 15:13:08 snips snips-skill-server[539]: ERROR:snips_skill_server_lib::runner            : action respeaker-makerskit failed 3 times in the last 10 seconds, disabling it
Jun  7 15:13:08 snips snips-skill-server[539]: WARN:snips_skill_server_lib::handler::nosandbox: child respeaker-makerskit has stopped with status `exit code: 1`
Jun  7 15:13:08 snips snips-skill-server[539]: INFO:snips_skill_server_lib::runner            : [respeaker-makerskit][err] RuntimeError: Failed to add edge detection
Jun  7 15:13:08 snips snips-skill-server[539]: INFO:snips_skill_server_lib::runner            : [respeaker-makerskit][err]     GPIO.add_event_detect(17, GPIO.FALLING, callback=hotword_toggle, bouncetime=300)
Jun  7 15:13:08 snips snips-skill-server[539]: INFO:snips_skill_server_lib::runner            : [respeaker-makerskit][err]   File "/var/lib/snips/skills/snips-skill-respeaker/snipsrespeaker/snipsrespeaker.py", line 145, in __init__
Jun  7 15:13:08 snips snips-skill-server[539]: INFO:snips_skill_server_lib::runner            : [respeaker-makerskit][err]     self.respeaker = SnipsRespeaker()
Jun  7 15:13:08 snips snips-skill-server[539]: INFO:snips_skill_server_lib::runner            : [respeaker-makerskit][err]   File "./action-respeaker-makerskit.py", line 25, in __init__
Jun  7 15:13:08 snips snips-skill-server[539]: INFO:snips_skill_server_lib::runner            : [respeaker-makerskit][err]     Skill()
Jun  7 15:13:08 snips snips-skill-server[539]: INFO:snips_skill_server_lib::runner            : [respeaker-makerskit][err]   File "./action-respeaker-makerskit.py", line 53, in <module>
Jun  7 15:13:08 snips snips-skill-server[539]: INFO:snips_skill_server_lib::runner            : [respeaker-makerskit][err] Traceback (most recent call last):
Jun  7 15:13:08 snips snips-skill-server[539]: INFO:snips_skill_server_lib::runner            : [respeaker-makerskit][out]
Jun  7 15:13:08 snips snips-skill-server[539]: INFO:snips_skill_server_lib::runner            : [respeaker-makerskit][out]   Subdevice #0: subdevice #0
Jun  7 15:13:08 snips snips-skill-server[539]: INFO:snips_skill_server_lib::runner            : [respeaker-makerskit][out]   Subdevices: 0/1
Jun  7 15:13:08 snips snips-skill-server[539]: INFO:snips_skill_server_lib::runner            : [respeaker-makerskit][out] card 1: seeed2micvoicec [seeed-2mic-voicecard], device 0: bcm2835-i2s-wm8960-hifi wm8960-hifi-0 []
Jun  7 15:13:08 snips snips-skill-server[539]: INFO:snips_skill_server_lib::runner            : [respeaker-makerskit][out] **** List of CAPTURE Hardware Devices ****
Jun  7 15:13:08 snips snips-skill-server[539]: INFO:snips_skill_server_lib::runner            : [respeaker-makerskit][out] u'configuration=\n'
Jun  7 15:13:08 snips snips-skill-server[539]: INFO:snips_skill_server_lib::runner            : [respeaker-makerskit][out] file: config.ini, line: 1
Jun  7 15:13:08 snips snips-skill-server[539]: INFO:snips_skill_server_lib::runner            : [respeaker-makerskit][out] File contains no section headers.

Any ideas? The permissions seem to be ok...

**Comment by jandru** [comment]
Still having this issue-
Jun 7 15:13:08 snips snips-skill-server[539]: INFO:snips_skill_server_lib::runner : [respeaker-makerskit][err] RuntimeError: Failed to add edge detection

**Comment by quartje** [comment]
I have this issue as well. Commenting out line 145 snipsrespeaker.py fixes the issue for me.

**Comment by jandru** [comment]
Thanks for the response quartje!
I did that too, commented lines 144 & 145 (after a lot of experimentation- and without "GPIO.add_event_detect" "GPIO.setup" doesn't do anything I can see). After commenting out the lines the LED works for the hotword recognition but the led's flash blue only and I cant seem to change the colors. Or maybe I am not understanding how to use the config.json or custom_config.json.

I can't figure out how the GPIO is being used. Maybe to receive data for MQTT events? The GPIO is set to pin 17; that is also the pin for the mic_hat GPIO button (see here: http://wiki.seeedstudio.com/ReSpeaker_2_Mics_Pi_HAT/   
See # 5. How to use User Button.

Also, I had to allow anonymous on my MQTT server (it's on a different Debian server), because action-respeaker-makerskit.py has no variables for MQTT username or password. I don't really want to use it this way though because I have a lot of data I'd like to keep at least minimally secure. BTW I am using Home Assistant on yet another server.

I really would like to get the led's to work with my color scheme and not just blue, and to get the MQTT fixed at least for basic security. I can change the MQTT_IP_ADDR and that works but only with anonymous access, and does not work with Mosquitto username and password security enabled on my system.

**Comment by fwehrle** [comment]
Hi,
I install the skill without problem. And spi is enabled and led working with seed studio python script.
But the skill didn't work for me.. Do I need to configure something?
I try to add the relative path of custom.json in config.ini, but it didn't work too..
Any advice?
Thx

**Comment by jandru** [comment]
fwehrle,

How did you install the skill? I found that installing the skill manually did not work for me. If you are using the ReSpeaker 2 mics hat as I am you can use sam setup audio. Sam installs the skill. Also check the snips logs and see why the skill is not working.

**Comment by fwehrle** [comment]
@jandru : thank you for trying to help me.
I effectivelly install the skill with sam install skills -g https://github.com/snipsco/snips-skill-respeaker.git
I launched sam setup audio, and it set up the asound.conf with the wrong card (hw0,0 but I'am on a pi3 so respeaker is card 1 : hw1,0). I change it manually, but both didn't play sound anymore.
So I revert to my previous working asound file with success.
But leds never blink.. :(
Which logs can I check? syslogs?

Edit : Nothing in syslog talks about skills or leds..

**Comment by jandru** [comment]
@fwehrle,
I disabled the onboard audio for the pi3b+ to prevent this problem. 
https://www.instructables.com/id/Disable-the-Built-in-Sound-Card-of-Raspberry-Pi/
Then I ran the sam setup audio.
I think I reflashed the image to clear out the old settings and begin from a known starting point. I never could get it to work once it was not working correctly.

**Comment by fwehrle** [comment]
Oh.. Ok. I'll try to disabled the onboard audio, and delete the skill. Thank you

**Comment by fwehrle** [comment]
YESS! I remove some others skills (google calendar), reload assistant, and it works!
One more question : did you achieve to install this skill on a satellite (pi0 with only snips-audio-server) ? Do I need to install other services (like skills-server)?

**Comment by jandru** [comment]
On the satellites I installed just snips-audio-server and snips-skill-server...

**Comment by jandru** [comment]
My satellites are pi3b+, not sure how the pi zero works with snips...

**Comment by fwehrle** [comment]
@jandru : I confirm you that snips-audio-server work nice on pi0w with respeaker 2mic array too.
I'll try to install snips-skills-server and this skill. 
Thank you for helping and advices.

**Comment by urbatecte** [comment]
@jandru and @fwehrle ,

As I was also struggling with LED on the respeaker (4 mics), I re-insatll fresh setup and try to follow the advice.
disable on board audio
then install respeaker skill with sam but when try to run am setup audio I get both error:
Error fetching audio capture device: arecord: device_list:270: no soundcards found
and
Error fetching audio output device: aplay: device_list:270: no soundcards found

I'am  bit lost... Is anything wrong in my steps ?
Thanks for your help

**Comment by jandru** [comment]
@urbatecte,

The respeaker 4 mic array does not have an audio output, so disabling the onboard audio will not work for you.

You will use the onboard audio for sound output.

**Comment by urbatecte** [comment]
@jandru ,

Arghhhhhhhhh., what a sad news !
Thanks for your fast feedback.
It's ok regarding the output device, but even with the respeaker skill there is no capture board found.
As for fwehrle, when I use seeed python script for LED, it work's.

Any hints  ?

**Comment by urbatecte** [comment]
@fwehrle 
I have the same config : respeaker 2mic hat + pi0w. Snips work fine but led still not work with the skill.
Have you succeed on your side ?
Thanks for your advice.

**Comment by CoorFun** [comment]
Hi Jandru,

Please complete remove the old respeaker skill folder then have the latest installed. 

We are now having a brand new respeaker skill. So please try to re-install the new one. I suppose you can fix the issue by this update. If you have any problem with using the new version. Please feel free to re-open this issue.
