### ISSUE TITLE
No assistant installed on satellite

### ISSUE THREAD

**Issue by fwehrle** [snipsco/snips-skill-respeaker#6]
Hi,

When I try to install the skill (with sam) on a snips satellite (with just audio and skill servers), sam tell me this errors : (and leds don't work)

pi@Snips-Server:~ $ sam install skills -g https://github.com/snipsco/snips-skill-respeaker.git
Checking for skills
✖ Error reading the Snipsfile for skills, reason: cat: /usr/share/snips/assistant/Snipsfile.yaml: Aucun fichier ou dossier de ce type
Cloning skill from url: https://github.com/snipsco/snips-skill-respeaker.git
Déjà à jour.

✔ Generating virtual environment for python actions

Checking actions for end-user parameters
Relaunching snips-skill-server
✖ Error: No assistant installed

Is there a way to install it on a satellite?

**Comment by fwehrle** [comment]
Ok. I finally installed a fake assistant, but it's not better.
Here is the log : 
`Sep  8 11:46:28 Snips-Parents snips-skill-server[1592]: INFO:snips_skill_server_lib::runner            : [respeaker-makerskit][err] Could not create hermes MQTT handler: Error(Io(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }), State { next_error: None, backtrace: None })
Sep  8 11:46:28 Snips-Parents snips-skill-server[1592]: INFO:snips_skill_server_lib::runner            : [respeaker-makerskit][err]
Sep  8 11:46:28 Snips-Parents snips-skill-server[1592]: INFO:snips_skill_server_lib::runner            : [respeaker-makerskit][err] Could not start MQTT client on localhost:1883
Sep  8 11:46:28 Snips-Parents snips-skill-server[1592]: INFO:snips_skill_server_lib::runner            : [respeaker-makerskit][err]  -> caused by: Could not start MQTT client on localhost:1883
Sep  8 11:46:28 Snips-Parents snips-skill-server[1592]: INFO:snips_skill_server_lib::runner            : [respeaker-makerskit][err]  -> caused by: Connection refused (os error 111)
Sep  8 11:46:28 Snips-Parents snips-skill-server[1592]: INFO:snips_skill_server_lib::runner            : [respeaker-makerskit][err]
Sep  8 11:46:28 Snips-Parents snips-skill-server[1592]: INFO:snips_skill_server_lib::runner            : [respeaker-makerskit][err] Segmentation fault
Sep  8 11:46:28 Snips-Parents snips-skill-server[1592]: WARN:snips_skill_server_lib::handler::nosandbox: child respeaker-makerskit has stopped with status `exit code: 139`
Sep  8 11:46:28 Snips-Parents snips-skill-server[1592]: INFO:snips_skill_server_lib::runner            : restarting action respeaker-makerskit (restart_fails: 2)`

**Comment by CoorFun** [comment]
Hi fwehrle, 

We have updated this respeaker skill. Now you can have it on satellite. 

Beware that:
1/ Having a `no assistant installed` warning/error is normal, this is just a message to let you know. Will not affect anything on led skill side. 

2/ When you install it on a satellite, please do refer the `README.md`to correctly set the `siteId` and `mqtt` connection in the `config.ini` file
