### ISSUE TITLE
Please add username and password for MQTT as configuration option

### ISSUE THREAD

**Issue by JasperZ** [snipsco/snips-skill-respeaker#8]
Hi,

I would like to use this skill on my Raspberry Pi Zero W running only the snips-audio-server as a sattelite device.
The problem is that I need a configuration option to set the username and password for an external MQTT server.

So I would suggest to add these as configuration options to the `config.ini` file like this:
```
# MQTT
mqtt_host=ip_address_of_host
mqtt_port=port_of_host
mqtt_username=username_used_for_mqtt
mqtt_password=password_used_for_mqtt
```

Thanks in advance
Jasper

**Comment by CoorFun** [comment]
Hi, 

Thanks for your feedback. I will implement it as soon as possible.

**Comment by CoorFun** [comment]
Hi Jasper, 

I have pushed the version that supports username/ password for mqtt connection on the branch `c-dev`. 

You can have a test for your use case. It will be merged to the `master` soon. 

To install this branch `c-dev`, you can use sam(On PC):
```
sam install actions -g https://github.com/snipsco/snips-skill-respeaker.git -b c-dev
```
***Beware that you may need to manually remove the old action code folder(On Raspberry): `/var/lib/snips/skills/snips-skill-respeaker`***

**Comment by JasperZ** [comment]
Hey,

I just tried it and it works great, no problems at all!
Thx for the quick implementation!!!
