### ISSUE TITLE
LED not working if snips-skill-server not running as root

### ISSUE THREAD

**Issue by dony71** [snipsco/snips-skill-respeaker#9]
default snips-skill-server.service will run as user _snips-skills and group _snips-skills
however LED is not working if not change user to root
i check directory /var/lib/snips/skills belong to _snips:_snips (default install by sam)
check also /etc/group has 
_snips-skills:x:114:_snips
snips-skills-admin:x:999:_snips
gpio:x:997:_snips-skills
spi:x:996:_snips-skills

**Comment by CoorFun** [comment]
Hello:

Which platform?

**Comment by dony71** [comment]
it's Raspberry Pi 3 running debian stretch 32-bit

**Comment by CoorFun** [comment]
Hello:

This is wired. On a fresh install of Raspbien, it should work without the root permission. Have you ever changed something? Also if possible, could you track a system log of starting the snips-skill-server?

By doing this:

First 
```
sudo systemctl stop snips-skill-server
```

Then, in another terminal window
```
tail -f /var/log/syslog
```

Finally,
```
sudo systemctl start snips-skill-server
```

You should now see a couple of lines log corresponding to respeaker led action.

**Comment by CoorFun** [comment]
Hello @dony71 : 

This issue should not exist if the `_snips-skills` user have the groups `spi` `i2c` `gpio` assigned. 

You probably need to manually perform a permission assignment to this user by doing:
```
sudo usermod -a -G spi,gpio,audio _snips-skills
```
I suppose all good with your testing and debugging, so I will close this issue for now. Please feel free to reopen this issue if you meet any trouble in the future. 

Thanks.
